name = "volo-app-local"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "Data", globs = ["**/*.data"], fallthrough = true }
]

[vars]
ENVIRONMENT = "development"

# Development tools configuration
[dev]
port = 8787
local_protocol = "http"