name = "{{WORKER_NAME}}"
main = "src/index.ts"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Development tools configuration
[dev]
port = 8787
local_protocol = "http"